openapi: "3.0.3"
info:
  title: Common components
  version: "ignore me"
paths: {}
components:
  schemas:
    jsonapi:
      description: The version of JSON:API being used.
      type: object
      additionalProperties: false
      required:
        - version
      properties:
        version:
          type: string
    id:
      type: string
      format: uuid
    linksSelf:
      type: object
      required:
        - self
      properties:
        self:
          type: string
          format: uri-reference
    linksPagination:
      type: object
      properties:
        first:
          type: string
          format: uri-reference
          nullable: true
        last:
          type: string
          format: uri-reference
          nullable: true
        next:
          type: string
          format: uri-reference
          nullable: true
        prev:
          type: string
          format: uri-reference
          nullable: true
    success:
      description: A JSON:API document with a link to it's own resource.
      type: object
      required:
        - jsonapi
        - data
        - links
      properties:
        jsonapi:
          $ref: "#/components/schemas/jsonapi"
        data:
          oneOf:
            - type: object
            - type: array
              items:
                type: object
        links:
          $ref: "#/components/schemas/linksSelf"
    single:
      description: A single resource.
      type: object
      required:
        - data
      properties:
        data:
          type: object
    many:
      description: A collection of resources, possibly paginated.
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          description: The collection of objects.
          type: array
          uniqueItems: true
          items:
            type: object
        links:
          allOf:
            - $ref: "#/components/schemas/linksSelf"
            - $ref: "#/components/schemas/linksPagination"
        meta:
          type: object
          required:
            - total
          properties:
            total:
              description: The total users that exist.
              type: integer
              format: int64
            page:
              description: The current page number if pagination is used.
              type: integer
              format: int64
              nullable: true
            pageSize:
              description: The number of users listed per page if pagination is used.
              type: integer
              format: int64
              nullable: true
            totalPages:
              description:
                The number of pages at the current page size, if pagination is
                used.
              type: integer
              format: int64
              nullable: true
