openapi: "3.0.3"
info:
  title: Common components
  version: "ignore me"
paths: {}
components:
  schemas:
    jsonapi:
      description: The version of JSON:API being used.
      type: object
      additionalProperties: false
      required:
        - version
      properties:
        version:
          type: string
    id:
      type: string
      format: uuid
    linksSelf:
      type: object
      required:
        - self
      properties:
        self:
          type: string
          format: uri-reference
    linksPagination:
      type: object
      properties:
        first:
          type: string
          format: uri-reference
          nullable: true
        last:
          type: string
          format: uri-reference
          nullable: true
        next:
          type: string
          format: uri-reference
          nullable: true
        prev:
          type: string
          format: uri-reference
          nullable: true
    success:
      description:
        A JSON:API success document with included data and a link to it's own
        resource.
        JSON:API requires use of the "application/vnd.api+json" media type for
        exchanging data.
      type: object
      required:
        - jsonapi
        - data
        - links
      properties:
        jsonapi:
          $ref: "#/components/schemas/jsonapi"
        data:
          oneOf:
            - type: object
            - type: array
              items:
                type: object
        links:
          $ref: "#/components/schemas/linksSelf"
    single:
      description: A single resource.
      type: object
      required:
        - data
      properties:
        data:
          type: object
    many:
      description: A collection of resources, possibly paginated.
      type: object
      required:
        - data
        - links
        - meta
      properties:
        data:
          description: The collection of objects.
          type: array
          uniqueItems: true
          items:
            type: object
        links:
          allOf:
            - $ref: "#/components/schemas/linksSelf"
            - $ref: "#/components/schemas/linksPagination"
        meta:
          type: object
          required:
            - total
          properties:
            total:
              description: The total users that exist.
              type: integer
              format: int64
            page:
              description: The current page number if pagination is used.
              type: integer
              format: int64
              nullable: true
            pageSize:
              description: The number of users listed per page if pagination is used.
              type: integer
              format: int64
              nullable: true
            totalPages:
              description:
                The number of pages at the current page size, if pagination is
                used.
              type: integer
              format: int64
              nullable: true
    error:
      type: object
      additionalProperties: false
      required:
        - status
        - code
        - title
      properties:
        status:
          description:
            The HTTP status code applicable to this problem, expressed as a string
            value.
          type: string
        code:
          description:
            An application-specific error code, expressed as a string value.
            For exceptions, this will be the exception type.
          type: string
        title:
          description:
            A short, human-readable summary of the problem. It **SHOULD NOT** change
            from occurrence to occurrence of the problem, except for purposes of
            localization.
            For exceptions, this will be the exception message.
          type: string
        detail:
          description:
            A human-readable explanation specific to this occurrence of the
            problem.
          type: string
        source:
          type: object
          properties:
            pointer:
              description:
                A JSON Pointer [RFC6901] to the associated entity in the request
                document [e.g. "/data" for a primary data object, or
                "/data/attributes/title" for a specific attribute].
              type: string
            parameter:
              description: A string indicating which query parameter caused the error.
              type: string
    failure:
      description:
        A JSON:API failure document with included errors nad a link to it's own
        resource.
        JSON:API requires use of the "application/vnd.api+json" media type for
        exchanging data.
      type: object
      additionalProperties: false
      required:
        - jsonapi
        - errors
        - links
      properties:
        errors:
          type: array
          uniqueItems: true
          items:
            $ref: "#/components/schemas/error"
        jsonapi:
          $ref: "#/components/schemas/jsonapi"
        links:
          $ref: "#/components/schemas/linksSelf"
    problemDetail:
      description:
        A Problem Detail [RFC7807] returned by the application framework.
        Usually occurs when validating input/output against this OpenAPI specification.
        When serialized as a JSON document, it is identified with the
        "application/problem+json" media type.
      type: object
      properties:
        type:
          description:
            A URI reference [RFC3986] that identifies the problem type.  This
            specification encourages that, when dereferenced, it provide human-readable
            documentation for the problem type.  When this member is not present, its
            value is assumed to be "about:blank".
          type: string
        title:
          description:
            A short, human-readable summary of the problem type.  It SHOULD NOT change
            from occurrence to occurrence of the problem, except for purposes of
            localization.
          type: string
        status:
          description:
            The HTTP status code ([RFC7231], Section 6) generated by the origin server
            for this occurrence of the problem.
          type: number
        detail:
          description:
            A human-readable explanation specific to this occurrence of the
            problem.
          type: string
        instance:
          description:
            A URI reference that identifies the specific occurrence of the problem.  It
            may or may not yield further information if dereferenced.
            (This property is believed to not actually be used by the current
            framework.)
          type: string
