openapi: "3.0.3"
info:
  title: GamesList Component
  version: "ignore me"
paths: {}
components:
  schemas:
    game:
      description: A single game resource along with a link to itself.
      type: object
      additionalProperties: false
      required:
        - type
        - id
        - links
        - relationships
      properties:
        type:
          type: string
        id:
          $ref: "common.yaml#/components/schemas/id"
        links:
          $ref: "common.yaml#/components/schemas/linksSelf"
        relationships:
          type: object
          required:
            - owner
          properties:
            owner:
              type: object
              required:
                - links
              properties:
                links:
                  $ref: "common.yaml#/components/schemas/linksRelated"
    gameSingle:
      description: A JSON:API document of a game resource.
      allOf:
        - $ref: "common.yaml#/components/schemas/success"
        - $ref: "common.yaml#/components/schemas/single"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/game"
    gameMany:
      description: A JSON:API document of a list of game resources, possibly paginated.
      allOf:
        - $ref: "common.yaml#/components/schemas/success"
        - $ref: "common.yaml#/components/schemas/many"
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/game"
