openapi: "3.0.3"
info:
  title: Race Card API
  version: "0.0.1"
  description: Race Card is an implementation of the card game Mille Bornes.
  contact:
    name: Krys Lawrence
    url: http://krys.ca
    email: "code@krys.ca"
  license:
    name: GNU AGPLv3+
    url: https://www.gnu.org/licenses/
tags:
  - name: games
    description: All API parts related to game resources.
  - name: users
    description: All API parts related to user resources.
servers:
  - url: /v0
    description: Pre-release version of API.  All things can change without notice.
paths:
  /games:
    get:
      operationId: games.search
      summary: A list of all the games that currently exist.
      tags: [games]
      responses:
        "200":
          description:
            Returns a list of game IDs and links for all the users that currently exist.
            Result is in JSON:API format.
          content:
            "application/vnd.api+json":
              schema:
                $ref: "#/components/schemas/gameMany"
  /users:
    get:
      operationId: users.search
      summary: A list all the users that currently exist.
      tags: [users]
      responses:
        "200":
          description:
            Returns a list of user IDs and links for all the users that currently exist.
            Result is in JSON:API format.
          content:
            "application/vnd.api+json":
              schema:
                $ref: "#/components/schemas/userMany"
  /users/{id}:
    get:
      operationId: users.get
      summary: Details about the user with the given id.
      tags: [users]
      parameters:
        - name: id
          in: path
          description: The id of the desired user, in UUID format.
          required: True
          schema:
            $ref: "#/components/schemas/id"
      responses:
        "200":
          description:
            Returns a details about the user and links to the games to which they are
            associated.
            Result is in JSON:API format.
          content:
            "application/vnd.api+json":
              schema:
                $ref: "#/components/schemas/userSingle"
components:
  schemas:
    id:
      $ref: "common.yaml#/components/schemas/id"
    gameMany:
      $ref: "game.yaml#/components/schemas/gameMany" # Included by prance
    userSingle:
      $ref: "user.yaml#/components/schemas/userSingle" # Included by prance
    userMany:
      $ref: "user.yaml#/components/schemas/userMany" # Included by prance
