openapi: "3.0.3"
info:
  title: UserList Component
  version: "ignore me"
paths: {}
components:
  schemas:
    user:
      description: A single user resource along with a link to itself.
      type: object
      additionalProperties: false
      required:
        - type
        - id
        - links
      properties:
        type:
          type: string
        id:
          $ref: "common.yaml#/components/schemas/id"
        attributes:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        links:
          $ref: "common.yaml#/components/schemas/linksSelf"
    userSingle:
      description: A JSON:API document of a user resource.
      allOf:
        - $ref: "common.yaml#/components/schemas/success"
        - $ref: "common.yaml#/components/schemas/single"
        - type: object
          properties:
            data:
              $ref: "#/components/schemas/user"
    userMany:
      description: A JSON:API document of a list of user resources, possibly paginated.
      allOf:
        - $ref: "common.yaml#/components/schemas/success"
        - $ref: "common.yaml#/components/schemas/many"
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: "#/components/schemas/user"
