openapi: "3.0.2"
info:
  title: UserList Component
  version: "0.0.1"
paths: {}
components:
  schemas:
    userList:
      description:
        List of users games in JSON:API format, possibly paginated if the list is
        large.
      type: object
      additionalProperties: false
      required:
        - jsonapi
        - data
        - links
        - meta
      properties:
        jsonapi:
          description: The version of JSON:API being used.
          type: object
          additionalProperties: false
          required:
            - version
          properties:
            version:
              type: string
        data:
          description: The list of users that currently exist along with links to them.
          type: array
          uniqueItems: true
          items:
            type: object
            additionalProperties: false
            required:
              - type
              - id
              - links
            properties:
              type:
                type: string
              id:
                type: string
                format: uuid
              attributes:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                    format: email
              links:
                type: object
                additionalProperties: false
                required:
                  - self
                properties:
                  self:
                    type: string
                    format: uri-reference
        links:
          description: Links for the list itself and any pagination resources if needed.
          type: object
          additionalProperties: false
          required:
            - self
          properties:
            self:
              type: string
              format: uri-reference
            first:
              type: string
              format: uri-reference
              nullable: true
            last:
              type: string
              format: uri-reference
              nullable: true
            next:
              type: string
              format: uri-reference
              nullable: true
            prev:
              type: string
              format: uri-reference
              nullable: true
        meta:
          type: object
          additionalProperties: false
          required:
            - total
          properties:
            total:
              description: The total users that exist.
              type: integer
              format: int64
            page:
              description: The current page number if pagination is used.
              type: integer
              format: int64
              nullable: true
            pageSize:
              description: The number of users listed per page if pagination is used.
              type: integer
              format: int64
              nullable: true
            totalPages:
              description:
                The number of pages at the current page size, if pagination is
                used.
              type: integer
              format: int64
              nullable: true
