openapi: "3.0.3"
info:
  title: UserList Component
  version: "ignore me"
paths: {}
components:
  schemas:
    user:
      description: A single user resource along with a link to itself.
      type: object
      additionalProperties: false
      required:
        - type
        - id
        - links
      properties:
        type:
          type: string
        id:
          $ref: "common.yaml#/components/schemas/id"
        attributes:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
              format: email
        links:
          $ref: "common.yaml#/components/schemas/linksSelf"
    userList:
      description: A list of users along with links to them.
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/user"
    userListDoc:
      description: A JSON:API document of a list of user resources, possibly paginated.
      allOf:
        - $ref: "common.yaml#/components/schemas/document"
        - $ref: "common.yaml#/components/schemas/collection"
        - $ref: "#/components/schemas/userList"
